server:
  name: "project-user"
  addr: "0.0.0.0:8080"#改为docker后不能127.0.0.1了
zap:
  DebugFileName: "/logs/debug/project-debug.log"#本机："D:\\GoWorks\\project\\ms_project\\logs\\debug\\project-debug.log"，改为docker后也要改
  InfoFileName: "/logs/info/project-info.log"
  WarnFileName: "/logs/error/project-error.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3
redis:
  host: "redis6"#用的docker中的容器名
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "0.0.0.0:8881"#原来本机："127.0.0.1:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"#原来："127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject
